#!/usr/bin/env python3
"""Create, inspect, and roll back the isolated JEV integration environment.

The environment is a self-contained directory under ``.jev/isolated`` holding

* ``home/config.toml`` - a Codex home whose provider points at the loopback
  fixture service and whose feature switches come from the chosen profile;
* ``bin/codex-isolated`` - the launcher that runs the pinned binary against
  that home;
* ``isolated-env.json`` - the resolved plan (profile, features, binary, port);
* ``logs/`` - fixture request records and invocation records.

Nothing outside the environment directory is written, and rollback only ever
moves that directory aside, so an existing user Codex home and any running
session are never touched.

Exit codes: 0 = ok, 1 = validation failure, 2 = usage error.
"""

import argparse
import json
import os
import shutil
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import jev_manifest
import offline_fixtures

ENV_VERSION = 1
DEFAULT_PROFILE = "isolated-offline"
DEFAULT_FIXTURE_PORT = 8756
DEFAULT_MODEL = "koffing"
LAUNCHER_REL = "bin/codex-isolated"


class EnvError(Exception):
    """The environment cannot be built or read as requested."""


def repository_root():
    return jev_manifest.repository_root()


def default_env_dir(root=None):
    return Path(root or repository_root()) / ".jev" / "isolated"


def superseded_dir(root=None):
    return Path(root or repository_root()) / ".jev" / "superseded"


def load_manifest(root=None):
    root = Path(root or repository_root())
    return jev_manifest.load_json(
        root / "jev" / "compatibility-manifest.json", "compatibility manifest"
    )


def load_profile(profile_id, root=None):
    root = Path(root or repository_root())
    profile_path = root / "jev" / "profiles" / f"{profile_id}.json"
    profile = jev_manifest.load_json(profile_path, f"profile {profile_id}")
    errors = jev_manifest.validate_manifest(
        load_manifest(root), repo_root=root, profile=profile
    )
    if errors:
        raise EnvError(f"profile {profile_id} is not a supported combination: {errors}")
    return profile


def resolve_plan(
    profile_id=DEFAULT_PROFILE,
    root=None,
    binary=None,
    port=DEFAULT_FIXTURE_PORT,
    model=DEFAULT_MODEL,
):
    """Resolve the isolated environment plan without writing anything."""
    root = Path(root or repository_root())
    manifest = load_manifest(root)
    profile = load_profile(profile_id, root)
    features = jev_manifest.effective_features(manifest, profile)
    optional_enabled = sorted(
        name
        for name, enabled in features.items()
        if enabled and not manifest["features"][name].get("default")
    )
    if optional_enabled:
        raise EnvError(
            "the isolated environment requires every optional feature to start "
            f"disabled, but {profile_id} enables: {', '.join(optional_enabled)}"
        )
    binary = Path(binary) if binary else default_binary(root)
    return {
        "env_version": ENV_VERSION,
        "profile": profile_id,
        "profile_digest": jev_manifest.sha256_file(
            root / "jev" / "profiles" / f"{profile_id}.json"
        ),
        "host_commit": manifest["host"]["base_commit"],
        "features": dict(sorted(features.items())),
        "optional_features_enabled": optional_enabled,
        "remote_inference": {
            "enabled": bool(features.get("remote_inference.enabled")),
            "consent": manifest["credentials"]["remote_inference"]["consent"],
        },
        "binary": str(binary),
        "binary_sha256": jev_manifest.sha256_file(binary) if binary.is_file() else None,
        "model": model,
        "fixture_port": port,
        "fixture_base_url": f"http://127.0.0.1:{port}/v1",
        "fixture_catalog": offline_fixtures.fixture_catalog(
            offline_fixtures.load_fixtures(root / "jev" / "fixtures")
        ),
    }


def default_binary(root):
    return Path(root) / "codex-rs" / "target" / "debug" / "codex"


def config_toml(plan):
    """Render the isolated Codex home config.

    The Codex-native ``[features]`` table is deliberately left out: the JEV
    switches are integration-level toggles, not Codex feature flags, and every
    optional one starts disabled here. They are recorded in ``jev-profile.json``
    and exported to the launcher as ``JEV_SWITCH_*`` variables so later phases
    read one contract instead of guessing at upstream flags.
    """
    lines = [
        "# Generated by jev/scripts/isolated_env.py - do not edit by hand.",
        f"# profile: {plan['profile']} (digest {plan['profile_digest']})",
        f"# host commit: {plan['host_commit']}",
        "# No Codex-native feature flag is enabled by the isolated profile; the",
        "# JEV switches live in ../jev-profile.json and JEV_SWITCH_* at launch.",
        f'model = "{plan["model"]}"',
        'model_provider = "jev_offline"',
        'approval_policy = "never"',
        'sandbox_mode = "read-only"',
        "",
        "[model_providers.jev_offline]",
        'name = "JEV offline fixtures"',
        f'base_url = "{plan["fixture_base_url"]}"',
        'wire_api = "responses"',
        'experimental_bearer_token = "offline-fixture"',
    ]
    return "\n".join(lines) + "\n"


def switch_name(feature):
    """The environment name one feature switch is read under."""
    return "JEV_SWITCH_" + feature.upper().replace(".", "_")


def switch_env(plan):
    """The ``JEV_SWITCH_*`` environment contract for one plan.

    These are the variables a launched host reads, so they carry the full
    documented prefix: the plan's own ``features`` mapping is the plain-name
    view of the same state.
    """
    return {
        switch_name(feature): ("1" if enabled else "0")
        for feature, enabled in plan["features"].items()
    }


def bus_env(plan, root=None):
    """The jev-bus boundary variables an isolated host runs under.

    The host invokes the repository's adapter exactly once per outgoing request
    when a projection switch above is on; the adapter itself reads the
    ``JEV_SWITCH_*`` state. Stage commands are not invented here: a stage is
    only registered when the environment supplies its command, so an
    unconsummated profile registers nothing.
    """
    root = Path(root or repository_root())
    return {
        "JEV_BUS_ADAPTER": str(root / "jev" / "scripts" / "bus_boundary.py"),
        "JEV_BUS_PYTHON": sys.executable or "python3",
        "JEV_BUS_WORKSPACE": str(plan.get("home") or ""),
    }


def launcher_script(env_dir, plan):
    return (
        "#!/bin/sh\n"
        "# Generated by jev/scripts/isolated_env.py - do not edit by hand.\n"
        "set -eu\n"
        f'ENV_DIR="{env_dir}"\n'
        f'REPO_ROOT="{repository_root()}"\n'
        'exec python3 "$REPO_ROOT/jev/scripts/launch_isolated.py" \\\n'
        f'  --env-dir "$ENV_DIR" -- "$@"\n'
    )


def init_env(
    env_dir=None,
    profile_id=DEFAULT_PROFILE,
    root=None,
    binary=None,
    port=DEFAULT_FIXTURE_PORT,
    model=DEFAULT_MODEL,
    force=False,
):
    """Materialise the isolated environment and return the written plan."""
    env_dir = Path(env_dir) if env_dir else default_env_dir(root)
    if env_dir.exists() and any(env_dir.iterdir()) and not force:
        raise EnvError(
            f"{env_dir} already exists; rerun with --force after reviewing, or "
            "roll it back first"
        )
    plan = resolve_plan(profile_id, root=root, binary=binary, port=port, model=model)
    home = env_dir / "home"
    (env_dir / "bin").mkdir(parents=True, exist_ok=True)
    (env_dir / "logs").mkdir(parents=True, exist_ok=True)
    home.mkdir(parents=True, exist_ok=True)
    (home / "config.toml").write_text(config_toml(plan), encoding="utf-8")
    launcher = env_dir / LAUNCHER_REL
    launcher.write_text(launcher_script(env_dir, plan), encoding="utf-8")
    launcher.chmod(0o755)
    plan["env_dir"] = str(env_dir)
    plan["home"] = str(home)
    plan["config"] = str(home / "config.toml")
    plan["launcher"] = str(launcher)
    plan["switch_env"] = switch_env(plan)
    plan["created_at_unix_ms"] = None
    (env_dir / "isolated-env.json").write_text(
        json.dumps(plan, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    (env_dir / "jev-profile.json").write_text(
        json.dumps(
            {
                "profile": plan["profile"],
                "profile_digest": plan["profile_digest"],
                "features": plan["features"],
                "switch_env": plan["switch_env"],
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )
    return plan


def read_env(env_dir=None, root=None):
    env_dir = Path(env_dir) if env_dir else default_env_dir(root)
    record = env_dir / "isolated-env.json"
    if not record.is_file():
        raise EnvError(f"no isolated environment at {env_dir}")
    return json.loads(record.read_text(encoding="utf-8"))


def status(env_dir=None, root=None):
    env_dir = Path(env_dir) if env_dir else default_env_dir(root)
    plan = read_env(env_dir)
    binary = Path(plan["binary"])
    present = binary.is_file()
    # A binary that is not on disk cannot match the plan, even when the plan
    # recorded no hash because the build had not run yet.
    current_sha = jev_manifest.sha256_file(binary) if present else None
    return {
        "env_dir": str(env_dir),
        "profile": plan["profile"],
        "host_commit": plan["host_commit"],
        "binary": plan["binary"],
        "binary_present": present,
        "binary_matches_plan": present and current_sha == plan.get("binary_sha256"),
        "optional_features_enabled": plan["optional_features_enabled"],
        "remote_inference_enabled": plan["remote_inference"]["enabled"],
    }


def rollback(env_dir=None, root=None, stamp=None, target_root=None):
    """Move the isolated environment aside; never delete another directory."""
    env_dir = Path(env_dir) if env_dir else default_env_dir(root)
    if not env_dir.exists():
        return {"env_dir": str(env_dir), "moved_to": None, "state": "absent"}
    stamp = stamp or time.strftime("%Y%m%dT%H%M%SZ", time.gmtime())
    base = Path(target_root) if target_root else superseded_dir(root)
    target = base / f"{env_dir.name}-{stamp}"
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists():
        raise EnvError(f"rollback target already exists: {target}")
    shutil.move(str(env_dir), str(target))
    return {"env_dir": str(env_dir), "moved_to": str(target), "state": "moved"}


def ambient_home_fingerprint():
    """Describe the ambient Codex home without reading its contents."""
    home = Path(os.environ.get("CODEX_HOME") or (Path.home() / ".codex"))
    return {
        "path": str(home),
        "exists": home.exists(),
        "config_present": (home / "config.toml").is_file(),
    }


def parse_args(argv):
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    init = sub.add_parser("init", help="Create the isolated environment.")
    init.add_argument("--env-dir", default=None)
    init.add_argument("--root", default=None)
    init.add_argument("--profile", default=DEFAULT_PROFILE)
    init.add_argument("--binary", default=None)
    init.add_argument("--port", type=int, default=DEFAULT_FIXTURE_PORT)
    init.add_argument("--model", default=DEFAULT_MODEL)
    init.add_argument("--force", action="store_true")

    for name, help_text in (
        ("status", "Report the isolated environment state."),
        ("rollback", "Move the isolated environment aside."),
    ):
        command = sub.add_parser(name, help=help_text)
        command.add_argument("--env-dir", default=None)
        command.add_argument("--root", default=None)
        if name == "rollback":
            command.add_argument("--stamp", default=None)
            command.add_argument("--target-root", default=None)
    return parser.parse_args(argv)


def main(argv=None):
    args = parse_args(argv if argv is not None else sys.argv[1:])
    try:
        if args.command == "init":
            plan = init_env(
                env_dir=args.env_dir,
                profile_id=args.profile,
                root=args.root,
                binary=args.binary,
                port=args.port,
                model=args.model,
                force=args.force,
            )
            print(json.dumps(plan, indent=2, sort_keys=True))
            return 0
        if args.command == "status":
            print(json.dumps(status(args.env_dir, args.root), indent=2, sort_keys=True))
            return 0
        result = rollback(
            args.env_dir, args.root, args.stamp, target_root=args.target_root
        )
        print(json.dumps(result, indent=2, sort_keys=True))
        return 0
    except (EnvError, jev_manifest.ManifestError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
